import type { Product } from "@/types/product";
import type { Seller, Customer, Admin } from "@/types/user";
import type { Order } from "@/types/order";

export const mockCategories = [
  { name: "Electronics", slug: "electronics", color: "bg-blue-50 text-blue-700 border-blue-100" },
  { name: "Fashion", slug: "fashion", color: "bg-pink-50 text-pink-700 border-pink-100" },
  { name: "Beauty & Health", slug: "beauty-health", color: "bg-purple-50 text-purple-700 border-purple-100" },
  { name: "Grocery", slug: "grocery", color: "bg-green-50 text-green-700 border-green-100" },
  { name: "Home & Office", slug: "home-office", color: "bg-yellow-50 text-yellow-700 border-yellow-100" },
  { name: "Computing", slug: "computing", color: "bg-indigo-50 text-indigo-700 border-indigo-100" },
  { name: "Stationery", slug: "stationery", color: "bg-orange-50 text-orange-700 border-orange-100" },
  { name: "Sports", slug: "sports", color: "bg-red-50 text-red-700 border-red-100" },
];

export const mockSellers: Seller[] = [
  {
    id: "seller-1",
    email: "greenstore@myproducts.co.ke",
    phone: "+254 700 100 001",
    name: "James Mwangi",
    role: "seller",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&q=80",
    storeName: "GreenStore KE",
    storeSlug: "greenstore",
    storeDescription: "Your one-stop shop for fresh groceries and organic produce delivered same-day in Nairobi.",
    storeRating: 4.8,
    totalSales: 2847,
    totalRevenue: 842000,
    productCount: 48,
    isVerified: true,
    plan: "growth",
    categories: ["Grocery", "Home & Office"],
    location: "Westlands, Nairobi",
    createdAt: "2023-03-15",
    joinedAt: "2023-03-15",
  },
  {
    id: "seller-2",
    email: "techhub@myproducts.co.ke",
    phone: "+254 700 100 002",
    name: "Sarah Njoroge",
    role: "seller",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&q=80",
    storeName: "TechHub KE",
    storeSlug: "techhub",
    storeDescription: "Kenya's leading electronics and computing store. Authorized dealer for Sony, Samsung, Anker and more.",
    storeRating: 4.6,
    totalSales: 1543,
    totalRevenue: 5240000,
    productCount: 132,
    isVerified: true,
    plan: "business",
    categories: ["Electronics", "Computing"],
    location: "CBD, Nairobi",
    createdAt: "2023-01-10",
    joinedAt: "2023-01-10",
  },
  {
    id: "seller-3",
    email: "styleco@myproducts.co.ke",
    phone: "+254 700 100 003",
    name: "Grace Wanjiru",
    role: "seller",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=80&h=80&fit=crop&q=80",
    storeName: "Style & Co",
    storeSlug: "styleco",
    storeDescription: "Trendy fashion for the modern African woman and man. Affordable prices, fast delivery.",
    storeRating: 4.3,
    totalSales: 890,
    totalRevenue: 1870000,
    productCount: 74,
    isVerified: false,
    plan: "starter",
    categories: ["Fashion"],
    location: "Kilimani, Nairobi",
    createdAt: "2024-02-20",
    joinedAt: "2024-02-20",
  },
  {
    id: "seller-4",
    email: "beautycorner@myproducts.co.ke",
    phone: "+254 700 100 004",
    name: "Amina Hassan",
    role: "seller",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=80&h=80&fit=crop&q=80",
    storeName: "Beauty Corner",
    storeSlug: "beautycorner",
    storeDescription: "Authentic beauty and skincare products. Dermatologist tested and skin-safe.",
    storeRating: 4.9,
    totalSales: 2103,
    totalRevenue: 3420000,
    productCount: 56,
    isVerified: true,
    plan: "growth",
    categories: ["Beauty & Health"],
    location: "Westlands, Nairobi",
    createdAt: "2023-06-05",
    joinedAt: "2023-06-05",
  },
];

export const mockProducts: Product[] = [
  // --- ELECTRONICS ---
  {
    id: "prod-1",
    name: "Sony WF-1000XM5 Wireless Earbuds",
    category: "Electronics",
    price: 18500,
    originalPrice: 22000,
    stock: 12,
    maxStock: 30,
    status: "live",
    sales: 143,
    views: 2840,
    sku: "ELC-001",
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&q=80",
    description: "Industry-leading noise canceling with Auto NC Optimizer. Crystal clear hands-free calling with 5 microphones. Up to 24 hours total battery life with charging case. Multipoint connection: stay connected to two devices simultaneously.",
    brand: "Sony",
    rating: 4.7,
    reviewCount: 89,
    sellerId: "seller-2",
    sellerName: "TechHub KE",
    isFeatured: true,
    isFlashDeal: true,
  },
  {
    id: "prod-2",
    name: "Anker USB-C to USB-C Cable 1m",
    category: "Electronics",
    price: 950,
    stock: 85,
    maxStock: 200,
    status: "live",
    sales: 430,
    views: 1200,
    sku: "ELC-002",
    image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400&h=400&fit=crop&q=80",
    description: "PowerLine III USB-C Cable. Double-braided nylon exterior for maximum durability. Supports 100W charging and 480Mbps data transfer. Compatible with all USB-C devices including laptops, phones, and tablets.",
    brand: "Anker",
    rating: 4.5,
    reviewCount: 215,
    sellerId: "seller-2",
    sellerName: "TechHub KE",
    isFlashDeal: true,
  },
  {
    id: "prod-3",
    name: "Baseus 20000mAh Power Bank 65W",
    category: "Electronics",
    price: 3200,
    originalPrice: 4500,
    stock: 28,
    maxStock: 60,
    status: "live",
    sales: 187,
    views: 3100,
    sku: "ELC-003",
    image: "https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400&h=400&fit=crop&q=80",
    description: "20000mAh high-capacity power bank with 65W PD fast charging. Charges a laptop from 0 to 50% in under 45 minutes. Slim profile, dual USB-A and USB-C output. Digital display shows exact battery percentage.",
    brand: "Baseus",
    rating: 4.6,
    reviewCount: 134,
    sellerId: "seller-2",
    sellerName: "TechHub KE",
    isFeatured: true,
    isNew: true,
  },
  {
    id: "prod-4",
    name: "JBL Flip 6 Bluetooth Speaker",
    category: "Electronics",
    price: 8900,
    originalPrice: 11000,
    stock: 15,
    maxStock: 40,
    status: "live",
    sales: 76,
    views: 1840,
    sku: "ELC-004",
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop&q=80",
    description: "Powerful JBL Pro Sound with separate tweeters and a woofer. IP67 waterproof and dustproof. 12 hours playtime. PartyBoost to connect multiple JBL speakers. Built-in microphone for speakerphone calls.",
    brand: "JBL",
    rating: 4.8,
    reviewCount: 62,
    sellerId: "seller-2",
    sellerName: "TechHub KE",
    isFlashDeal: true,
  },
  // --- FASHION ---
  {
    id: "prod-5",
    name: "Men's Premium Crew Neck T-Shirt",
    category: "Fashion",
    price: 1200,
    stock: 150,
    maxStock: 300,
    status: "live",
    sales: 342,
    views: 4200,
    sku: "FSH-001",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop&q=80",
    description: "100% combed cotton premium quality t-shirt. Pre-shrunk, anti-pilling fabric. Classic relaxed fit with ribbed crew neck. Machine washable. Available in 8 colors: Black, White, Navy, Grey, Green, Red, Blue, Maroon.",
    brand: "StyleKe",
    rating: 4.3,
    reviewCount: 178,
    sellerId: "seller-3",
    sellerName: "Style & Co",
    isFeatured: true,
  },
  {
    id: "prod-6",
    name: "Slim Fit Stretch Chino Pants",
    category: "Fashion",
    price: 3500,
    originalPrice: 4200,
    stock: 45,
    maxStock: 100,
    status: "live",
    sales: 120,
    views: 2100,
    sku: "FSH-002",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop&q=80",
    description: "Modern slim fit chino pants made with 2% elastane for all-day stretch and comfort. Wrinkle-resistant finish. 4 functional pockets. Available in Khaki, Navy, Olive, Black, and Stone. Sizes 28-40.",
    brand: "StyleKe",
    rating: 4.4,
    reviewCount: 87,
    sellerId: "seller-3",
    sellerName: "Style & Co",
  },
  {
    id: "prod-7",
    name: "Nike Air Max 270 Sneakers",
    category: "Fashion",
    price: 12500,
    originalPrice: 15000,
    stock: 8,
    maxStock: 20,
    status: "live",
    sales: 43,
    views: 3800,
    sku: "FSH-003",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&q=80",
    description: "Nike's biggest heel Air unit yet for a super-soft ride that feels as good as it looks. Mesh upper provides breathability. Foam midsole for cushioning. Available in sizes 38-46 EU.",
    brand: "Nike",
    rating: 4.8,
    reviewCount: 31,
    sellerId: "seller-3",
    sellerName: "Style & Co",
    isFeatured: true,
    isFlashDeal: true,
  },
  {
    id: "prod-8",
    name: "Women's Summer Floral Midi Dress",
    category: "Fashion",
    price: 2800,
    stock: 32,
    maxStock: 80,
    status: "live",
    sales: 95,
    views: 1650,
    sku: "FSH-004",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop&q=80",
    description: "Lightweight floral midi dress perfect for Nairobi's warm climate. 100% polyester, wrinkle-resistant. V-neck, short sleeves, flared A-line silhouette. Has side pockets. Available in sizes S to XXL.",
    brand: "Style & Co",
    rating: 4.2,
    reviewCount: 56,
    sellerId: "seller-3",
    sellerName: "Style & Co",
    isNew: true,
  },
  {
    id: "prod-9",
    name: "Genuine Leather Crossbody Bag",
    category: "Fashion",
    price: 4200,
    originalPrice: 5500,
    stock: 20,
    maxStock: 50,
    status: "live",
    sales: 67,
    views: 1900,
    sku: "FSH-005",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop&q=80",
    description: "Premium full-grain genuine leather crossbody bag. Adjustable shoulder strap (55-120cm). Multiple interior compartments including a zippered pocket. Fits up to a 10-inch tablet. Available in Black, Tan, and Brown.",
    brand: "LeatherCo",
    rating: 4.6,
    reviewCount: 43,
    sellerId: "seller-3",
    sellerName: "Style & Co",
    isFeatured: true,
  },
  // --- BEAUTY & HEALTH ---
  {
    id: "prod-10",
    name: "Vitamin C Brightening Face Serum 30ml",
    category: "Beauty & Health",
    price: 1850,
    stock: 40,
    maxStock: 100,
    status: "live",
    sales: 215,
    views: 3400,
    sku: "BTY-001",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop&q=80",
    description: "20% stabilized Vitamin C + Hyaluronic Acid + Niacinamide complex. Brightens skin tone, reduces dark spots and hyperpigmentation within 4 weeks. Dermatologist tested. Suitable for all skin types including sensitive skin.",
    brand: "GlowLab",
    rating: 4.7,
    reviewCount: 128,
    sellerId: "seller-4",
    sellerName: "Beauty Corner",
    isFeatured: true,
    isNew: true,
  },
  {
    id: "prod-11",
    name: "Long-Wearing Matte Lipstick",
    category: "Beauty & Health",
    price: 890,
    stock: 65,
    maxStock: 150,
    status: "live",
    sales: 310,
    views: 2800,
    sku: "BTY-002",
    image: "https://images.unsplash.com/photo-1586495777744-4e6232bf2919?w=400&h=400&fit=crop&q=80",
    description: "12-hour wear matte lipstick enriched with Vitamin E and aloe vera to keep lips moisturized all day. Transfer-proof and smudge-proof formula. 18 shades available from nudes to bold reds.",
    brand: "ColorPop KE",
    rating: 4.5,
    reviewCount: 195,
    sellerId: "seller-4",
    sellerName: "Beauty Corner",
    isFlashDeal: true,
  },
  {
    id: "prod-12",
    name: "Deep Hydration SPF 30 Day Cream",
    category: "Beauty & Health",
    price: 1450,
    stock: 55,
    maxStock: 120,
    status: "live",
    sales: 178,
    views: 2200,
    sku: "BTY-003",
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop&q=80",
    description: "SPF 30 broad spectrum protection with 48-hour deep hydration technology. Lightweight, non-greasy gel-cream formula absorbs in seconds. Suitable for all skin types including sensitive skin. Fragrance-free.",
    brand: "GlowLab",
    rating: 4.6,
    reviewCount: 97,
    sellerId: "seller-4",
    sellerName: "Beauty Corner",
  },
  {
    id: "prod-13",
    name: "Pure Moroccan Argan Hair Oil 100ml",
    category: "Beauty & Health",
    price: 1200,
    stock: 48,
    maxStock: 100,
    status: "live",
    sales: 142,
    views: 1900,
    sku: "BTY-004",
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop&q=80",
    description: "100% pure cold-pressed Moroccan argan oil. Repairs heat-damaged hair, adds brilliant shine, and reduces frizz instantly. Suitable for all hair types. Light, non-greasy texture absorbs fast without residue.",
    brand: "Organics KE",
    rating: 4.8,
    reviewCount: 76,
    sellerId: "seller-4",
    sellerName: "Beauty Corner",
  },
  {
    id: "prod-14",
    name: "Unrefined Shea Butter Body Cream 300ml",
    category: "Beauty & Health",
    price: 780,
    stock: 70,
    maxStock: 200,
    status: "live",
    sales: 264,
    views: 2100,
    sku: "BTY-005",
    image: "https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=400&h=400&fit=crop&q=80",
    description: "Rich unrefined Grade A shea butter cream. Deeply moisturizes dry, rough, and ashy skin. 100% natural, no parabens, sulfates, or artificial fragrances. Can be used on both body and face.",
    brand: "Organics KE",
    rating: 4.4,
    reviewCount: 143,
    sellerId: "seller-4",
    sellerName: "Beauty Corner",
    isFlashDeal: true,
  },
  // --- GROCERY ---
  {
    id: "prod-15",
    name: "Fresh Organic Vegetable Mix 1kg",
    category: "Grocery",
    price: 380,
    stock: 30,
    maxStock: 80,
    status: "live",
    sales: 412,
    views: 3200,
    sku: "GRC-001",
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400&h=400&fit=crop&q=80",
    description: "Farm-fresh mixed vegetables sourced daily from Kinangop, Nyandarua. Includes spinach, sukuma wiki, carrots, green beans, and broccoli. Washed and ready to cook. Same-day delivery in Nairobi.",
    brand: "GreenStore KE",
    rating: 4.8,
    reviewCount: 209,
    sellerId: "seller-1",
    sellerName: "GreenStore KE",
    isFeatured: true,
  },
  {
    id: "prod-16",
    name: "Brookside Full Cream Milk 1L",
    category: "Grocery",
    price: 85,
    stock: 120,
    maxStock: 300,
    status: "live",
    sales: 890,
    views: 4100,
    sku: "GRC-002",
    image: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=400&h=400&fit=crop&q=80",
    description: "Full cream pasteurized and homogenized milk. Rich in calcium, protein, and essential vitamins. Best-before: 7 days from delivery. Keep refrigerated. Order 6 or more packs for free delivery.",
    brand: "Brookside",
    rating: 4.6,
    reviewCount: 341,
    sellerId: "seller-1",
    sellerName: "GreenStore KE",
    isFlashDeal: true,
  },
  {
    id: "prod-17",
    name: "Artisan Sourdough Bread 500g",
    category: "Grocery",
    price: 320,
    stock: 25,
    maxStock: 50,
    status: "live",
    sales: 156,
    views: 1100,
    sku: "GRC-003",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop&q=80",
    description: "Traditional 48-hour long-fermented sourdough bread baked fresh daily in Nairobi. No preservatives or additives. Crispy golden crust with a chewy, airy crumb. Available sliced or whole.",
    brand: "Nairobi Bakehouse",
    rating: 4.7,
    reviewCount: 88,
    sellerId: "seller-1",
    sellerName: "GreenStore KE",
  },
  {
    id: "prod-18",
    name: "Kenyan Hass Avocados 6 Pack",
    category: "Grocery",
    price: 280,
    stock: 40,
    maxStock: 100,
    status: "live",
    sales: 325,
    views: 2400,
    sku: "GRC-004",
    image: "https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?w=400&h=400&fit=crop&q=80",
    description: "Premium Hass avocados from Murang'a County. 6-pack of medium-sized avocados delivered ripe and ready to eat. High in healthy monounsaturated fats, fiber, and potassium. Pesticide-free.",
    brand: "GreenStore KE",
    rating: 4.9,
    reviewCount: 167,
    sellerId: "seller-1",
    sellerName: "GreenStore KE",
    isFeatured: true,
  },
  {
    id: "prod-19",
    name: "Japanese Organic Sencha Green Tea 100g",
    category: "Grocery",
    price: 420,
    stock: 55,
    maxStock: 150,
    status: "live",
    sales: 188,
    views: 1700,
    sku: "GRC-005",
    image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=400&fit=crop&q=80",
    description: "Premium Japanese Sencha loose leaf green tea. Rich in antioxidants and EGCG. Yields 40-50 cups per 100g pack. Delicate grassy, sweet flavor. Certified organic by KEBS. Ideal morning or afternoon tea.",
    brand: "Teahouse KE",
    rating: 4.6,
    reviewCount: 93,
    sellerId: "seller-1",
    sellerName: "GreenStore KE",
    isNew: true,
  },
  // --- HOME & OFFICE ---
  {
    id: "prod-20",
    name: "LED Flexible Desk Lamp, USB Powered",
    category: "Home & Office",
    price: 1800,
    originalPrice: 2500,
    stock: 35,
    maxStock: 80,
    status: "live",
    sales: 124,
    views: 2100,
    sku: "HOM-001",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop&q=80",
    description: "3-level brightness LED desk lamp with warm, neutral, and cool white modes. USB-C powered, works with laptops, power banks, and adapters. 360° flexible gooseneck. Eye-care technology reduces blue light by 30%.",
    brand: "LightKe",
    rating: 4.4,
    reviewCount: 71,
    sellerId: "seller-2",
    sellerName: "TechHub KE",
    isFlashDeal: true,
  },
  {
    id: "prod-21",
    name: "Granite Non-Stick Cookware Set 5pcs",
    category: "Home & Office",
    price: 8500,
    originalPrice: 11000,
    stock: 18,
    maxStock: 40,
    status: "live",
    sales: 57,
    views: 1400,
    sku: "HOM-002",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&q=80",
    description: "5-piece granite non-stick cookware set. PFOA-free triple-layer granite coating. Includes: 20cm saucepan, 24cm frying pan, 26cm frying pan, 24cm casserole with lid. Compatible with all hobs including induction.",
    brand: "HomeKe",
    rating: 4.5,
    reviewCount: 38,
    sellerId: "seller-1",
    sellerName: "GreenStore KE",
    isFeatured: true,
  },
  // --- COMPUTING ---
  {
    id: "prod-22",
    name: "TKL Mechanical Gaming Keyboard RGB",
    category: "Computing",
    price: 7200,
    originalPrice: 9000,
    stock: 14,
    maxStock: 30,
    status: "live",
    sales: 48,
    views: 1650,
    sku: "CMP-001",
    image: "https://images.unsplash.com/photo-1595044426077-d36d9236d54a?w=400&h=400&fit=crop&q=80",
    description: "Tenkeyless mechanical gaming keyboard with Outemu Blue switches for tactile, clicky feedback. Full per-key RGB backlight with 18 lighting effects. N-key rollover for zero ghosting. Detachable USB-C braided cable.",
    brand: "GameZone KE",
    rating: 4.5,
    reviewCount: 34,
    sellerId: "seller-2",
    sellerName: "TechHub KE",
    isNew: true,
  },
  {
    id: "prod-23",
    name: "Anker 2.4GHz Wireless Silent Mouse",
    category: "Computing",
    price: 1650,
    stock: 52,
    maxStock: 100,
    status: "live",
    sales: 136,
    views: 1900,
    sku: "CMP-002",
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop&q=80",
    description: "2.4GHz wireless mouse with whisper-quiet click technology, 90% quieter than standard mice. Up to 18-month battery life on a single AA battery. Adjustable DPI 1200/2400/3200. 6 buttons. Nano USB receiver included.",
    brand: "Anker",
    rating: 4.6,
    reviewCount: 89,
    sellerId: "seller-2",
    sellerName: "TechHub KE",
  },
  // --- STATIONERY ---
  {
    id: "prod-24",
    name: "Hard Cover A4 Notebook 200 Pages",
    category: "Stationery",
    price: 350,
    stock: 200,
    maxStock: 500,
    status: "live",
    sales: 520,
    views: 3100,
    sku: "STN-001",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop&q=80",
    description: "A4 hard cover notebook with 200 ruled pages on 80gsm acid-free paper. Lay-flat binding. Includes elastic closure strap, expandable inner pocket, and fabric ribbon bookmark. Perfect for office or university use.",
    brand: "Scholar KE",
    rating: 4.4,
    reviewCount: 248,
    sellerId: "seller-1",
    sellerName: "GreenStore KE",
    isFlashDeal: true,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "cust-1",
    email: "john.kamau@gmail.com",
    phone: "+254 712 345 678",
    name: "John Kamau",
    role: "customer",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop&q=80",
    createdAt: "2024-01-15",
    addresses: [
      {
        id: "addr-1",
        label: "Home",
        street: "123 Ngong Road",
        city: "Nairobi",
        county: "Nairobi",
        isDefault: true,
      },
    ],
    loyaltyPoints: 340,
  },
  {
    id: "cust-2",
    email: "mary.njeri@gmail.com",
    phone: "+254 723 456 789",
    name: "Mary Njeri",
    role: "customer",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop&q=80",
    createdAt: "2024-02-20",
    addresses: [
      {
        id: "addr-2",
        label: "Home",
        street: "45 Mombasa Road",
        city: "Nairobi",
        county: "Nairobi",
        isDefault: true,
      },
    ],
    loyaltyPoints: 120,
  },
  {
    id: "cust-3",
    email: "peter.otieno@gmail.com",
    phone: "+254 734 567 890",
    name: "Peter Otieno",
    role: "customer",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&q=80",
    createdAt: "2024-03-10",
    addresses: [
      {
        id: "addr-3",
        label: "Office",
        street: "Upperhill Road",
        city: "Nairobi",
        county: "Nairobi",
        isDefault: true,
      },
    ],
    loyaltyPoints: 85,
  },
];

export const mockAdmin: Admin = {
  id: "admin-1",
  email: "admin@myproducts.co.ke",
  phone: "+254 700 000 000",
  name: "Platform Admin",
  role: "admin",
  permissions: ["all"],
  createdAt: "2023-01-01",
};

export const mockOrders: Order[] = [
  {
    id: "ORD-2024-001",
    customerId: "cust-1",
    customerName: "John Kamau",
    customerPhone: "+254 712 345 678",
    items: [
      {
        productId: "prod-1",
        productName: "Sony WF-1000XM5 Wireless Earbuds",
        productImage: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=80&h=80&fit=crop&q=80",
        sellerId: "seller-2",
        sellerName: "TechHub KE",
        quantity: 1,
        price: 18500,
        subtotal: 18500,
      },
    ],
    subtotal: 18500,
    deliveryFee: 0,
    total: 18500,
    status: "delivered",
    paymentMethod: "mpesa",
    paymentStatus: "paid",
    deliveryAddress: "123 Ngong Road, Nairobi",
    createdAt: "2024-05-10",
    updatedAt: "2024-05-13",
    trackingNumber: "MP2024001A",
  },
  {
    id: "ORD-2024-002",
    customerId: "cust-1",
    customerName: "John Kamau",
    customerPhone: "+254 712 345 678",
    items: [
      {
        productId: "prod-15",
        productName: "Fresh Organic Vegetable Mix 1kg",
        productImage: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=80&h=80&fit=crop&q=80",
        sellerId: "seller-1",
        sellerName: "GreenStore KE",
        quantity: 2,
        price: 380,
        subtotal: 760,
      },
      {
        productId: "prod-18",
        productName: "Kenyan Hass Avocados 6 Pack",
        productImage: "https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?w=80&h=80&fit=crop&q=80",
        sellerId: "seller-1",
        sellerName: "GreenStore KE",
        quantity: 1,
        price: 280,
        subtotal: 280,
      },
    ],
    subtotal: 1040,
    deliveryFee: 100,
    total: 1140,
    status: "shipped",
    paymentMethod: "mpesa",
    paymentStatus: "paid",
    deliveryAddress: "123 Ngong Road, Nairobi",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-02",
    estimatedDelivery: "2024-06-03",
    trackingNumber: "MP2024002B",
  },
  {
    id: "ORD-2024-003",
    customerId: "cust-2",
    customerName: "Mary Njeri",
    customerPhone: "+254 723 456 789",
    items: [
      {
        productId: "prod-10",
        productName: "Vitamin C Brightening Face Serum 30ml",
        productImage: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=80&h=80&fit=crop&q=80",
        sellerId: "seller-4",
        sellerName: "Beauty Corner",
        quantity: 1,
        price: 1850,
        subtotal: 1850,
      },
      {
        productId: "prod-14",
        productName: "Unrefined Shea Butter Body Cream",
        productImage: "https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=80&h=80&fit=crop&q=80",
        sellerId: "seller-4",
        sellerName: "Beauty Corner",
        quantity: 2,
        price: 780,
        subtotal: 1560,
      },
    ],
    subtotal: 3410,
    deliveryFee: 0,
    total: 3410,
    status: "processing",
    paymentMethod: "card",
    paymentStatus: "paid",
    deliveryAddress: "45 Mombasa Road, Nairobi",
    createdAt: "2024-06-02",
    updatedAt: "2024-06-02",
  },
  {
    id: "ORD-2024-004",
    customerId: "cust-1",
    customerName: "John Kamau",
    customerPhone: "+254 712 345 678",
    items: [
      {
        productId: "prod-22",
        productName: "TKL Mechanical Gaming Keyboard RGB",
        productImage: "https://images.unsplash.com/photo-1595044426077-d36d9236d54a?w=80&h=80&fit=crop&q=80",
        sellerId: "seller-2",
        sellerName: "TechHub KE",
        quantity: 1,
        price: 7200,
        subtotal: 7200,
      },
    ],
    subtotal: 7200,
    deliveryFee: 0,
    total: 7200,
    status: "pending",
    paymentMethod: "mpesa",
    paymentStatus: "pending",
    deliveryAddress: "123 Ngong Road, Nairobi",
    createdAt: "2024-06-02",
    updatedAt: "2024-06-02",
  },
  {
    id: "ORD-2024-005",
    customerId: "cust-3",
    customerName: "Peter Otieno",
    customerPhone: "+254 734 567 890",
    items: [
      {
        productId: "prod-7",
        productName: "Nike Air Max 270 Sneakers",
        productImage: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=80&h=80&fit=crop&q=80",
        sellerId: "seller-3",
        sellerName: "Style & Co",
        quantity: 1,
        price: 12500,
        subtotal: 12500,
      },
    ],
    subtotal: 12500,
    deliveryFee: 0,
    total: 12500,
    status: "confirmed",
    paymentMethod: "card",
    paymentStatus: "paid",
    deliveryAddress: "Upperhill Road, Nairobi",
    createdAt: "2024-06-01",
    updatedAt: "2024-06-01",
  },
];
